# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

#Autowire .env vars
parameters:
    frontendDomain: '%env(FRONTEND_DOMAIN)%'
    frontendDomainLoginCallbackEndpoint: '%env(FRONTEND_LOGIN_CALLBACK_ENDPOINT)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\Api\AuthController:
        arguments:
            $frontendDomain: '%frontendDomain%'
            $frontendLoginCallbackEndpoint: '%frontendDomainLoginCallbackEndpoint%'

