nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['%env(FRONTEND_DOMAIN)%']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: true
