security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api_public:
            pattern: ^/api/(login|register)
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt:
                provider: app_user_provider
                authenticator: lexik_jwt_authentication.security.jwt_authenticator

    access_control:
        - { path: ^/api/login,                      roles: PUBLIC_ACCESS }
        - { path: ^/api/login/google,               roles: PUBLIC_ACCESS }
        - { path: ^/api/login/google/cookie,        roles: PUBLIC_ACCESS }
        - { path: ^/api/register,                   roles: PUBLIC_ACCESS }
        - { path: ^/api,                            roles: IS_AUTHENTICATED_FULLY }
