services:
  backend:
    build:
      context: ./backend
    container_name: app
    ports:
      - "8000:8000"
      - "9999:9003"
    volumes:
      - ./backend:/var/www/html/app/backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/html/app/frontend
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
