services:
  backend:
    build:
      context: ./backend
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html/app/backend
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PHP_IDE_CONFIG: "serverName=naviServer"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/html/app/frontend
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  node_modules:
  vendor:
